version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    networks:
      - app_network
    
networks:
  app_network:
    driver: bridge


    
